from django.db import models

class Coin(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)
    price = models.FloatField()
    grade = models.CharField(max_length=100)
    sold = models.CharField(max_length=50)
    obverse_description = models.CharField(max_length=255)
    reverse_description = models.CharField(max_length=255)
    km_number = models.CharField(max_length=50)
    weight = models.FloatField()
    numiscorner_id = models.IntegerField()
    product_url = models.CharField(max_length=255)
    country = models.CharField(max_length=100)
    denomination = models.CharField(max_length=100)
    year = models.CharField(max_length=100)
    coin_condition = models.CharField(max_length=100)
    mint_name = models.CharField(max_length=100)
    composition = models.CharField(max_length=100)
    coinage_type = models.CharField(max_length=100)
    diameter = models.FloatField()
    first_issue_date = models.CharField(max_length=100)
    mintage = models.IntegerField
    period = models.CharField(max_length=100)
    ruler_name = models.CharField(max_length=100)
    theoretical_coin_weight = models.FloatField()
    edge_lettering = models.CharField(max_length=255)
    mint_mark = models.CharField(max_length=100)
    coin_name = models.CharField(max_length=100)
    mint_location = models.CharField(max_length=100)
    edge_desc = models.CharField(max_length=100)
    specific_remark = models.CharField(max_length=100)
    actual_weight = models.FloatField()
    fineness = models.FloatField()
    geographic_area = models.CharField(max_length=100)
    strike_mark = models.CharField(max_length=50)
    subject = models.CharField(max_length=100)
    main_character = models.CharField(max_length=100)
    series = models.CharField(max_length=100)
    coin_shape = models.CharField(max_length=100)
    certification = models.CharField(max_length=100)
    certification_number = models.IntegerField()
    series_theme = models.CharField(max_length=100)

    def __str__(self) -> str:
        return ' '.join([self.denomination, self.country])

class Image(models.Model):
    coin = models.ForeignKey(Coin, on_delete=models.CASCADE)
    obverse_image_url = models.CharField(max_length=255)
    reverse_image_url  = models.CharField(max_length=255)
    obverse_image = models.ImageField(upload_to='numiscorner')
    reverse_image = models.ImageField(upload_to='numiscorner')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
