# Generated by Django 4.1.3 on 2022-11-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='product_url',
            field=models.CharField(max_length=255),
        ),
    ]
