# Generated by Django 4.1.3 on 2022-11-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0002_alter_coin_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='obverse_image',
            field=models.ImageField(upload_to='numiscorner'),
        ),
        migrations.AlterField(
            model_name='image',
            name='reverse_image',
            field=models.ImageField(upload_to='numiscorner'),
        ),
    ]
