# Generated by Django 4.1.3 on 2022-12-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0003_alter_image_obverse_image_alter_image_reverse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='mintage',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
    ]
