# Generated by Django 4.1.3 on 2022-12-05 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0005_coin_date_created_coin_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coin',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
