# Generated by Django 4.1.3 on 2022-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0006_alter_coin_date_created_alter_coin_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
