# Generated by Django 4.1.3 on 2022-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0007_alter_coin_date_created_alter_coin_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='actual_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='certification_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='fineness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mintage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='numiscorner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='theoretical_coin_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='obverse_image',
            field=models.ImageField(default='../media/numiscorner/default_o.jpg', upload_to='numiscorner'),
        ),
        migrations.AlterField(
            model_name='image',
            name='reverse_image',
            field=models.ImageField(default='../media/numiscorner/default_r.jpg', upload_to='numiscorner'),
        ),
    ]
