# Generated by Django 4.1.3 on 2022-12-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0011_alter_image_obverse_image_alter_image_reverse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='obverse_image',
            field=models.ImageField(null=True, upload_to='numiscorner'),
        ),
        migrations.AlterField(
            model_name='image',
            name='obverse_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='reverse_image',
            field=models.ImageField(null=True, upload_to='numiscorner'),
        ),
        migrations.AlterField(
            model_name='image',
            name='reverse_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
