# Generated by Django 4.1.3 on 2022-12-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0012_alter_image_obverse_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
