# Generated by Django 4.1.3 on 2022-12-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0013_image_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='obverse_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='obverse_image_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='reverse_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='reverse_image_url',
        ),
        migrations.AlterField(
            model_name='coin',
            name='certification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_shape',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='coinage_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='composition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='denomination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='edge_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='edge_lettering',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='first_issue_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='geographic_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='km_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coin',
            name='main_character',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mint_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mint_mark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mint_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='obverse_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='product_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='ruler_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='series',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='series_theme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='sold',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coin',
            name='specific_remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='strike_mark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coin',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
