# Generated by Django 4.1.3 on 2022-12-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0015_alter_coin_certification_alter_coin_coin_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='coin',
            new_name='coin_id',
        ),
    ]
