# Generated by Django 4.1.3 on 2022-12-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0016_rename_coin_image_coin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='coin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='numiscorner.coin'),
        ),
    ]
