# Generated by Django 4.1.3 on 2022-12-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0018_alter_image_coin_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('order',)},
        ),
    ]
