# Generated by Django 4.1.3 on 2022-12-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiscorner', '0019_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pictogram',
            field=models.ImageField(null=True, upload_to='numiscorner/pictograms'),
        ),
    ]
